MODEL:
  TYPE: vssm
  NAME: vssm_tiny
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 4, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v1"
    PATCHEMBED: "v2"
    # SSM_FORWARDTYPE: "v0" # if you want exactly the same